//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CombackStorage
    {
        public int CombStId { get; set; }
        public int CobId { get; set; }
        public int DeliId { get; set; }
        public int DelSId { get; set; }
        public int ComNum { get; set; }
    
        public virtual Comeback Comeback { get; set; }
        public virtual Deliver Deliver { get; set; }
        public virtual DeliverStorage DeliverStorage { get; set; }
    }
}
