//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deliver
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Deliver()
        {
            this.CombackStorage = new HashSet<CombackStorage>();
            this.DeliverStorage = new HashSet<DeliverStorage>();
        }
    
        public int DeliId { get; set; }
        public string DeliType { get; set; }
        public string DeliaOrder { get; set; }
        public System.DateTime DelDate { get; set; }
        public int CusId { get; set; }
        public string DeliPerson { get; set; }
        public System.DateTime CreateTime { get; set; }
        public int IsDelete { get; set; }
        public string Remake { get; set; }
        public int AudiId { get; set; }
    
        public virtual Auditing Auditing { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CombackStorage> CombackStorage { get; set; }
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeliverStorage> DeliverStorage { get; set; }
    }
}
