//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GarageShift
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GarageShift()
        {
            this.GarageShiftStorage = new HashSet<GarageShiftStorage>();
        }
    
        public int GarSId { get; set; }
        public string GarSType { get; set; }
        public int AudiId { get; set; }
        public string GarSOrder { get; set; }
        public string GarSPerson { get; set; }
        public System.DateTime CreateTime { get; set; }
        public int IsDelete { get; set; }
        public string Remake { get; set; }
    
        public virtual Auditing Auditing { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GarageShiftStorage> GarageShiftStorage { get; set; }
    }
}
