//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CangChuEntities1 : DbContext
    {
        public CangChuEntities1()
            : base("name=CangChuEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admin { get; set; }
        public virtual DbSet<Auditing> Auditing { get; set; }
        public virtual DbSet<CombackStorage> CombackStorage { get; set; }
        public virtual DbSet<Comeback> Comeback { get; set; }
        public virtual DbSet<Customer> Customer { get; set; }
        public virtual DbSet<CustomerAdd> CustomerAdd { get; set; }
        public virtual DbSet<Damage> Damage { get; set; }
        public virtual DbSet<DamageStorage> DamageStorage { get; set; }
        public virtual DbSet<Deliver> Deliver { get; set; }
        public virtual DbSet<DeliverStorage> DeliverStorage { get; set; }
        public virtual DbSet<Dept> Dept { get; set; }
        public virtual DbSet<GarageShift> GarageShift { get; set; }
        public virtual DbSet<GarageShiftStorage> GarageShiftStorage { get; set; }
        public virtual DbSet<Probaict> Probaict { get; set; }
        public virtual DbSet<ProbaictCatagory> ProbaictCatagory { get; set; }
        public virtual DbSet<ProbaictStorage> ProbaictStorage { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Storehouse> Storehouse { get; set; }
        public virtual DbSet<Storehousetype> Storehousetype { get; set; }
        public virtual DbSet<Supplier> Supplier { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Unit> Unit { get; set; }
        public virtual DbSet<Vendor> Vendor { get; set; }
        public virtual DbSet<Warehouse> Warehouse { get; set; }
        public virtual DbSet<WarehouseStorage> WarehouseStorage { get; set; }
    }
}
