//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Probaict
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Probaict()
        {
            this.DamageStorage = new HashSet<DamageStorage>();
            this.DeliverStorage = new HashSet<DeliverStorage>();
            this.GarageShiftStorage = new HashSet<GarageShiftStorage>();
            this.ProbaictStorage = new HashSet<ProbaictStorage>();
            this.WarehouseStorage = new HashSet<WarehouseStorage>();
        }
    
        public string ProId { get; set; }
        public string ProName { get; set; }
        public decimal ProPrice { get; set; }
        public string PorGuiGe { get; set; }
        public int ProCId { get; set; }
        public int UnId { get; set; }
        public System.DateTime CreateTime { get; set; }
        public int ProNumber { get; set; }
        public int ProJinhuo { get; set; }
        public int ProChuhuo { get; set; }
        public int ProBaosun { get; set; }
        public int IsDelete { get; set; }
        public string Remake { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DamageStorage> DamageStorage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeliverStorage> DeliverStorage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GarageShiftStorage> GarageShiftStorage { get; set; }
        public virtual ProbaictCatagory ProbaictCatagory { get; set; }
        public virtual Unit Unit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProbaictStorage> ProbaictStorage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WarehouseStorage> WarehouseStorage { get; set; }
    }
}
